D_dev_agg <- read.table("../../GitHubData/converted/dev_agg.csv", sep = ",", header = T)
names(D_dev_agg)
load("../../Rdata/project_stars.RData")
# D <-# read.table(../../GitHubData/converted/result_stargazers_2013_final_mature_stars.csv,# sep=;, header=T)
names(D)
D$repository_fork <- as.numeric(D$repository_fork)
D$repository_has_wiki <- as.numeric(D$repository_has_wiki)
D$repository_has_issues <- as.numeric(D$repository_has_issues)
D$repository_has_downloads <- as.numeric(D$repository_has_downloads)
D_agg <- merge(D, D_dev_agg, by = "repository_url")
D_agg <- D_agg[D_agg$stargazers_count > 0, ]
nrow(D_agg)
ggplot(D_agg, aes(x = average.work_for_company, y = stargazers_count)) + geom_point() + geom_smooth() + geom_smooth(method = lm, color = "red")
ggplot(D_agg, aes(x = log(average.followers), y = stargazers_count)) + geom_point() + geom_smooth() + geom_smooth(method = lm, color = "red")